-- undrmnd v2 content seed — 30 rows, rewritten to the open-question bar.
-- Ratio: 12 contribute · 9 read · 9 reflect.  Pillars: cosmos, living_world,
-- mind_and_brain, how_we_know (climate folded into living_world; health into
-- mind_and_brain).  All rows flagged is_open_question = true; is_active = false
-- until a human reads each one and flips it on.

begin;

insert into content_items
  (title, hook, body, interaction_type, tags,
   source_citation, source_url, action_url, topic,
   estimated_time_minutes, is_open_question, is_active, contributed_by)
values

-- ===== COSMOS (8) =====

-- Sample kept verbatim: dark matter.
('What is dark matter, really?',
 '85% of the matter in the universe is invisible, and no one knows what it''s made of.',
 'We know it''s there because galaxies rotate faster than their visible mass allows. We don''t know what particle — if any particle — it actually is. For 40 years, the leading theory has been WIMPs; in 2025, the leading theory is axions; ask again in 2030. This is a question the field is actively, publicly losing sleep over.',
 'contribute',
 array['dark_matter','cosmology','open_question','citizen_science'],
 'Kuchner et al., Astrophysical Journal, 2017',
 'https://doi.org/10.3847/1538-4357/aa6c5d',
 'https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9',
 'cosmos', 10, true, false, 'teo_ok'),

('Is there a Planet Nine hiding in our own solar system?',
 'The outer orbits of a handful of trans-Neptunian objects are clustered in a way nothing in the current solar system should cause.',
 'Batygin and Brown predicted a ninth planet from the clustering in 2016. No one has seen it. The Vera C. Rubin Observatory, which came online in 2025, is expected to find it within its first survey cycle — or rule it out. You can help search the existing WISE infrared data in the meantime.',
 'contribute',
 array['planet_nine','solar_system','open_question'],
 'Batygin & Brown, Astronomical Journal, 2016',
 'https://doi.org/10.3847/0004-6256/151/2/22',
 'https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9',
 'cosmos', 10, true, false, 'teo_ok'),

('Why is the universe expanding faster than it should?',
 'Two trusted methods of measuring the universe''s expansion rate give two different numbers. Neither side has found the mistake.',
 'The "Hubble tension" has only gotten worse with JWST data. Either one of the measurements is systematically wrong in a way no one has caught, or the standard cosmological model is missing a piece. Both are interesting answers.',
 'read',
 array['cosmology','hubble_tension','open_question'],
 'Riess et al., ApJL, 2022',
 'https://doi.org/10.3847/2041-8213/ac5c5b',
 null,
 'cosmos', 4, true, false, 'juno_rx'),

('Classify a galaxy no machine has seen clearly yet',
 'Humans still beat algorithms at identifying spiral arms in noisy images.',
 'Galaxy Zoo''s volunteers have out-classified the first generation of automated classifiers, and their labels are the training data for the next generation. A single classification takes about 15 seconds.',
 'contribute',
 array['galaxies','citizen_science','zooniverse'],
 'Lintott et al., MNRAS, 2008',
 'https://doi.org/10.1111/j.1365-2966.2008.13689.x',
 'https://www.zooniverse.org/projects/zookeeper/galaxy-zoo/',
 'cosmos', 5, true, false, 'sage_m'),

('Find Jupiter tonight',
 'No telescope needed. It''s the brightest "star" in the southeast sky after sunset.',
 'NASA''s night-sky calendar tells you what''s visible, where you are. Step outside. Count one second for every moon you can resolve — binoculars show three or four.',
 'observe',
 array['astronomy','naked_eye','nasa'],
 'NASA Night Sky Network',
 'https://nightsky.jpl.nasa.gov/',
 'https://nightsky.jpl.nasa.gov/planet-guide.cfm',
 'cosmos', 5, true, false, 'nneka_o'),

('Is there a ninth note in cosmic microwave background?',
 'The faint echo of the Big Bang has statistical anomalies no theory fully explains.',
 'Planck data shows a "cold spot" and a hemispheric asymmetry that the standard inflationary model doesn''t predict. It might be a statistical fluke, or it might be evidence of something outside our observable universe. The debate is open.',
 'reflect',
 array['cosmology','cmb','open_question'],
 'Planck Collaboration, A&A, 2020',
 'https://doi.org/10.1051/0004-6361/201833910',
 null,
 'cosmos', 4, true, false, 'juno_rx'),

('Hunt for a supernova no one else has seen',
 'Supernova Hunters on Zooniverse sends you real-time telescope images. Spot one, confirm it, it''s yours.',
 'The Pan-STARRS telescope produces more transient alerts than professionals can review. Volunteer classifications have led to real co-discoveries. Five minutes gets you onto the reviewer pool.',
 'contribute',
 array['supernova','citizen_science','zooniverse'],
 'Wright et al., MNRAS, 2017',
 'https://doi.org/10.1093/mnras/stx1812',
 'https://www.zooniverse.org/projects/dwright04/supernova-hunters',
 'cosmos', 10, true, false, 'marco_dz'),

('Look at a 1,000-year-old star map',
 'The Dunhuang Star Chart is the oldest known graphical representation of the full sky. The stars are accurate.',
 'Made around 700 CE in Tang dynasty China, digitized and public-domain via the British Library and Library of Congress. Zoom in on the constellations — the ancient names don''t match ours and that itself is interesting.',
 'read',
 array['astronomy','history_of_science','public_domain'],
 'Dunhuang Star Chart, British Library / LoC',
 'https://www.loc.gov/item/2021668393/',
 null,
 'cosmos', 3, true, false, 'ilhan_b'),

-- ===== LIVING WORLD (8) =====

('How many species share Earth with us? No one knows within a factor of 10.',
 'Estimates range from 2 million to a trillion. Most of the uncertainty is microbes.',
 'Locey and Lennon''s 2016 model is the high end; others argue it''s an overestimate. Every new rainforest survey and every new deep-sea expedition shifts the number. You can contribute a data point without leaving your block.',
 'contribute',
 array['biodiversity','open_question','citizen_science'],
 'Locey & Lennon, PNAS, 2016',
 'https://doi.org/10.1073/pnas.1521291113',
 'https://www.inaturalist.org/',
 'living_world', 10, true, false, 'nneka_o'),

('Does the "wood-wide web" actually work the way Simard said?',
 'A 1997 Nature paper said trees trade carbon through fungal networks. A 2023 review says the evidence is thinner than popular science made it sound.',
 'Carbon transfer through mycorrhizal networks is real. What''s contested is whether trees are "communicating" in any meaningful sense, or whether the fungi are the ones running the show. This is what active scientific disagreement looks like.',
 'read',
 array['ecology','fungi','open_question','scientific_debate'],
 'Karst, Jones & Hoeksema, Nature Ecology & Evolution, 2023',
 'https://doi.org/10.1038/s41559-023-01986-1',
 null,
 'living_world', 5, true, false, 'yuki_t'),

('Identify one plant on your walk',
 'Open iNaturalist. Point the camera at a leaf. Confirm the suggestion, or skip.',
 'Every observation that reaches "research grade" becomes CC-licensed data that real biodiversity models use. You''re not playing; you''re adding a dot to the global map.',
 'contribute',
 array['biodiversity','citizen_science','inaturalist'],
 'iNaturalist / California Academy of Sciences',
 'https://www.inaturalist.org/pages/seek_app',
 'https://www.inaturalist.org/',
 'living_world', 6, true, false, 'sage_m'),

('Why did the last Ice Age end so fast?',
 'The shift out of the last glacial maximum happened in centuries, not millennia. Current climate models struggle to reproduce it.',
 'Ice cores, ocean sediments, and cave formations all agree on the speed. What''s debated is the trigger — ocean circulation, orbital forcing, feedback loops, or some combination no one has modeled correctly yet.',
 'reflect',
 array['climate','paleoclimate','open_question'],
 'Shakun et al., Nature, 2012',
 'https://doi.org/10.1038/nature10915',
 null,
 'living_world', 5, true, false, 'priya_lk'),

('Log a rain gauge reading',
 'NOAA''s Community Collaborative Rain, Hail & Snow network takes data from anyone with a gauge.',
 'It has run for 27 years. Schools, retirees, and farmers submit most of the readings. If you want to do one small, real science thing this week, this is it.',
 'contribute',
 array['climate','citizen_science','noaa'],
 'CoCoRaHS, NOAA/NSF',
 'https://www.cocorahs.org/',
 'https://www.cocorahs.org/Application.aspx',
 'living_world', 10, true, false, 'marco_dz'),

('Why do some reefs recover from bleaching and others don''t?',
 'The answer is partly genetics and partly timing, and no one knows the weights.',
 'Hughes et al. tracked reefs through consecutive bleaching events. Recovery correlated with time between shocks, but so do a dozen other factors. The coral gene banks that might answer this are being built right now.',
 'read',
 array['ocean','ecology','climate','open_question'],
 'Hughes et al., Nature, 2018',
 'https://doi.org/10.1038/s41586-018-0041-2',
 null,
 'living_world', 4, true, false, 'yuki_t'),

('Help transcribe a 100-year-old plant specimen',
 'Museums have millions of pressed plants with handwritten labels that no OCR can read.',
 'Notes from Nature (Zooniverse) converts them into records for GBIF, which climate researchers use to track range shifts. Ten minutes, one specimen, one more dot on a map that matters.',
 'contribute',
 array['citizen_science','biodiversity','zooniverse'],
 'Notes from Nature, Zooniverse',
 'https://www.zooniverse.org/projects/md68135/notes-from-nature-herbarium-specimens',
 'https://www.zooniverse.org/projects/md68135/notes-from-nature-herbarium-specimens',
 'living_world', 10, true, false, 'ilhan_b'),

('What makes an octopus''s intelligence different from a vertebrate''s?',
 'Two thirds of an octopus''s neurons are in its arms, not its head. Whether it "thinks" with them is an open question.',
 'Octopuses pass cognitive tests designed for vertebrates, but they last solved a common ancestor with us 600 million years ago. Their intelligence evolved independently. It''s the closest thing we have to studying an alien mind.',
 'reflect',
 array['cognition','animal_intelligence','open_question'],
 'Mather, Consciousness and Cognition, 2008',
 'https://doi.org/10.1016/j.concog.2006.09.006',
 null,
 'living_world', 4, true, false, 'priya_lk'),

-- ===== MIND & BRAIN (8) =====

-- Sample kept verbatim: consciousness.
('Is consciousness something physics can describe?',
 'We don''t have a theory that explains why there''s a "what it''s like" to be you.',
 'You can describe every neuron firing in a brain and still not account for the fact that experience is happening. Philosophers call this the hard problem; most working neuroscientists avoid the phrase because it feels unscientific. But two theories — Integrated Information Theory and Global Workspace Theory — have been in a public, pre-registered adversarial collaboration since 2023, actively trying to disprove each other with real experiments. The answer is not in.',
 'reflect',
 array['consciousness','neuroscience','open_question','philosophy'],
 'Melloni et al., Nature, 2023',
 'https://doi.org/10.1038/s41586-023-06345-5',
 null,
 'mind_and_brain', 5, true, false, 'sage_m'),

('Why do we sleep? The honest answer: we''re still figuring it out.',
 'Memory consolidation, waste clearance, circuit pruning — each theory explains part of the data and none explains all of it.',
 'Xie et al. showed the glymphatic system clears metabolic waste during deep sleep. But that''s one function of many, and sleep in fruit flies and jellyfish predates the structures that theory relies on. Sleep is older than brains.',
 'read',
 array['sleep','neuroscience','open_question'],
 'Xie et al., Science, 2013',
 'https://doi.org/10.1126/science.1241224',
 null,
 'mind_and_brain', 4, true, false, 'teo_ok'),

('Sit with one open question for 60 seconds',
 'If a computer perfectly simulated your brain, would there be something it was like to be that simulation?',
 'There''s no right answer. The fact that the question is still open is the card. When the timer ends, the card ends too.',
 'reflect',
 array['consciousness','philosophy','reflection'],
 'Chalmers, Journal of Consciousness Studies, 1995',
 'https://consc.net/papers/facing.pdf',
 null,
 'mind_and_brain', 1, true, false, 'sage_m'),

('Help tag the emotions in a film clip',
 'The HUME project collects human emotion labels to train models — and to find out where humans disagree with each other.',
 'The surprise in the early data: cross-cultural agreement on some emotions, big divergence on others. Your labels become part of that dataset. Ten minutes to onboard, as long as you want after that.',
 'contribute',
 array['emotion','cognition','citizen_science'],
 'Cowen & Keltner, PNAS, 2017',
 'https://doi.org/10.1073/pnas.1702247114',
 'https://www.hume.ai/',
 'mind_and_brain', 10, true, false, 'nneka_o'),

('Why do phones feel impossible to put down?',
 'Intermittent reinforcement: the same mechanic as slot machines. You don''t know when the next reward is coming, so you keep pulling.',
 'Skinner showed this in pigeons in 1957. Social apps re-implemented it in 2009. Knowing the mechanism doesn''t break the loop — but it does let you notice when you''re inside one.',
 'reflect',
 array['attention','design_ethics','dark_patterns'],
 'Lyngs et al., CHI, 2019',
 'https://doi.org/10.1145/3290605.3300361',
 null,
 'mind_and_brain', 3, true, false, 'juno_rx'),

('Do antidepressants work through serotonin? The textbook answer may be wrong.',
 'A 2022 umbrella review found no consistent evidence that depression is caused by a serotonin imbalance.',
 'SSRIs still help many people, but the mechanism behind that help is now openly contested. This is one of the biggest open questions in clinical psychiatry and you can read the primary paper yourself.',
 'read',
 array['health','psychiatry','open_question'],
 'Moncrieff et al., Molecular Psychiatry, 2022',
 'https://doi.org/10.1038/s41380-022-01661-0',
 null,
 'mind_and_brain', 5, true, false, 'priya_lk'),

('Try a four-breath pause',
 'In for four. Hold for four. Out for four. Hold for four. One cycle.',
 'Balban et al. compared breathing protocols in a controlled trial. Cyclic sighing beat mindfulness meditation on same-day mood. The mechanism is vagal; the trial is small; the question of whether it scales is open.',
 'observe',
 array['breathing','stress','micro_intervention'],
 'Balban et al., Cell Reports Medicine, 2023',
 'https://doi.org/10.1016/j.xcrm.2022.100895',
 null,
 'mind_and_brain', 2, true, false, 'marco_dz'),

('Is "flow state" a real neurological thing?',
 'The phenomenology is well described. The neural signature is still being debated.',
 'Csíkszentmihályi defined flow in 1975 from interviews. Neuroimaging studies since 2010 have produced inconsistent markers. Whether flow is a distinct brain state or a cluster of related states is an open question — one that matters to musicians, athletes, writers, and surgeons.',
 'reflect',
 array['flow','cognition','open_question'],
 'van der Linden et al., Neurosci. & Biobehav. Reviews, 2021',
 'https://doi.org/10.1016/j.neubiorev.2020.11.032',
 null,
 'mind_and_brain', 4, true, false, 'yuki_t'),

-- ===== HOW WE KNOW (6) =====

('Why is the replication crisis not a scandal?',
 'Somewhere between 36% and 65% of published psychology findings don''t replicate. That''s not a failure — it''s the system working.',
 'The Open Science Collaboration''s 2015 replication of 100 psychology studies was the turning point. Pre-registration, open data, and replication are now expected in top journals. The "crisis" was the cure.',
 'read',
 array['history_of_science','replication','open_science'],
 'Open Science Collaboration, Science, 2015',
 'https://doi.org/10.1126/science.aac4716',
 null,
 'how_we_know', 4, true, false, 'ilhan_b'),

('Citizen science predates professional science',
 'Linnaeus''s classification system ran on amateur observers mailing him specimens for decades.',
 'The split between "professional" and "amateur" science is a 20th-century invention. Darwin, Mendel, Maria Mitchell — most of the people in your textbook didn''t have the job title.',
 'reflect',
 array['history_of_science','citizen_science'],
 'Hajibayova, JASIST, 2019',
 'https://doi.org/10.1002/asi.24248',
 null,
 'how_we_know', 4, true, false, 'sage_m'),

('Read a real lab notebook from 1905',
 'Marie Curie''s lab notebooks are digitized, in the public domain, and still radioactive.',
 'The physical books are lead-lined at the Bibliothèque Nationale de France. The digitized pages are free to look at. Her handwriting tells you she was tired a lot.',
 'read',
 array['history_of_science','marie_curie','primary_source'],
 'BNF Gallica — Marie Curie Notebooks',
 'https://gallica.bnf.fr/ark:/12148/bpt6k14752x',
 'https://gallica.bnf.fr/ark:/12148/bpt6k14752x',
 'how_we_know', 6, true, false, 'nneka_o'),

('Help proofread an open-access paper',
 'PubPeer is an open post-publication peer review platform. Anyone can flag a statistics error, a suspicious figure, or a sloppy citation.',
 'Several retractions of high-impact papers started as a comment from an anonymous PubPeer user. Reading a paper critically is itself a skill, and this is the place to practice it in public.',
 'contribute',
 array['open_science','peer_review','citizen_science'],
 'Blatt et al., Cell, 2015',
 'https://doi.org/10.1016/j.cell.2014.12.023',
 'https://pubpeer.com/',
 'how_we_know', 15, true, false, 'marco_dz'),

('Can AI review science papers better than humans?',
 'Early experiments say it can replicate median reviewer judgments. Whether that''s a compliment to the AI or an indictment of median reviewers is an open question.',
 'Liang et al. had GPT-4 generate reviews for Nature and ICLR submissions; the overlap with human reviewers was 50–80%. Peer review is more contested now than at any point since it became standard.',
 'reflect',
 array['open_science','peer_review','ai','open_question'],
 'Liang et al., NEJM AI, 2024',
 'https://doi.org/10.1056/AIoa2400196',
 null,
 'how_we_know', 4, true, false, 'juno_rx'),

('What would it take for citizen science to just be called "science"?',
 'The data quality is already there. The gatekeeping is social, not technical.',
 'A 2021 review in Science found that well-designed citizen-science projects match professional quality on the tasks they''re designed for. The remaining barrier is co-authorship credit, funding access, and publication norms — all human systems, all changeable.',
 'read',
 array['citizen_science','open_question','equity'],
 'Fraisl et al., Nature Reviews Methods Primers, 2022',
 'https://doi.org/10.1038/s43586-022-00144-4',
 null,
 'how_we_know', 5, true, false, 'teo_ok');

commit;
